### ISSUE TITLE
Code review.

### ISSUE THREAD

**Issue by kgryte** [dstructs/array#1]
The initial motivation for this module was to extract the following which is used quite frequently in `compute` modules.

``` javascript
dt = dtype || 'float64';
ctor = ctors( dt );
if ( ctor === null ) {
  throw new Error( '...' );
}
return new ctor( len );
```

This module manages to cover this use case, but may also be considered a precursor for a future `vector` class (possible `array` subclass).

**Note**: any future extension to this module should be non-breaking, as in accessing elements should not change => `a[ i ] === a'[ i ]`. I could foresee something akin to the `Array.prototype` module you wrote, except without binding methods to the prototype and sharing a closer similarity to `matrix`. Definitely, not a priority atm.

**Comment by Planeshifter** [comment]
Changed two lines in the JSDOC documentation and bumped the `chai` version range to `3.x.x`, everything else looks well to me. Agreed that we might want to provide some utility methods to manipulate / access data from arrays. But we can publish this as an initial version, I think, and use it in our other modules.

**Comment by kgryte** [comment]
Cool. Thanks for the thorough review and spotting the mistakes!
